### PR TITLE
Remove blank lines

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Test comment

**Comment by filipemarinheiro** [comment]
My new comment

**Comment by filipemarinheiro** [comment]
My new comment

**Comment by filipemarinheiro** [comment]
My new comment

**Comment by filipemarinheiro** [comment]
My new comment

**Comment by filipemarinheiro** [comment]
My new comment

**Comment by filipemarinheiro** [comment]
My new comment

**Comment by filipemarinheiro** [comment]
My new comment

**Comment by filipemarinheiro** [comment]
My new comment

**Comment by filipemarinheiro** [comment]
My new comment2

**Comment by filipemarinheiro** [comment]
My new comment

**Comment by filipemarinheiro** [comment]
My new comment3

**Pull request closed without merging**
